version: '2'
services:

  www:
    build: www/.
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

  db:
    build: db/.
    volumes_from:
      - dbdata
    environment:
       MYSQL_ROOT_PASSWORD: supersecure

  dbdata:
    build: data/.
    hostname: mysqldata
